Convolution directory
esl-epfl/ESL-CGRA-simulator pull request #20
Opened 2024-04-30 13:23 UTC by NicCarp11

This pull request includes the convolution directory, which contains the 4 parallelism implemented:

- weight parallelism
- input channel parallelism
- output channel parallelism with direct convolution
- output channel parallelism with im2col
For each of them it was implemented one example, in order to help the understanding of their functionalities. 

Please review and merge these changes as appropriate. Thank you!

2024-05-01 12:33 UTC, JuanSapriza requested changes
Two major comments: 
1) Are you sure that a convolution can be executed from the example notebook with this? Without trying I would say not. Maybe leave everything ready so that by default someone running the example will use the WP approach. 
2) Some organization changes I did a while back would be reverted in this PR. Please pull, merge and push again to this branch :)

Minor comments: 
1) Remove unused files
2) Remove unused comments, and flatten the input/weight arrays a bit so that they dont take thousands of lines. 

THANK YOU VERY MUCH! Many people will make great use of this!

2024-05-01 12:33 UTC, JuanSapriza commented on .vscode/settings.json
> +{
Can we remove the `.vscode` folder? 
```
git rm --cached .vscode
```
we can also add it to the gitignore :)

2024-05-01 12:33 UTC, JuanSapriza commented on examples/convolution/convolution_C/convolution
What is this file? Can we remove it?

2024-05-01 12:33 UTC, JuanSapriza commented on examples/convolution/convolution_C/convolution.c
> +{{
Can we have this in a more friendly way? e.g. having it in a header file, or having each array in the same line (so that it takes waaay less lines)

2024-05-01 12:33 UTC, JuanSapriza commented on examples/convolution/convolution_C/matmul.c
> +// input 3 channels
Please erase comments

2024-05-01 12:33 UTC, JuanSapriza commented on examples/convolution/convolution_C/im2col
Same with this and any other file without extension

2024-05-01 12:33 UTC, JuanSapriza commented on examples/convolution/convolution_channel_output_parallelism/number_instr_output_parallelism.csv
What is this file? Can we remove it?

2024-05-01 12:33 UTC, JuanSapriza commented on src/counter_instr.py
> +            'LW': {},  # Unifica LWD e LWI in LW
Please switch comments to english

2024-05-01 12:33 UTC, JuanSapriza commented on INTRODUCTION.ipynb
This file was added by me in a previous version. 
IMPORTANT: please PULL from main, merge (and make sure that changes that I previously made will be kept) and then push again :)

2024-05-07 10:42 UTC, NicCarp11 commented
Thanks @JuanSapriza for the comments. I modify according to your suggestions. 
N.B. You can find now just the weight parallelism methods, because with the new version of the simulator I need to test better the other 3 methods. In any case, I tested the wp and it works. 
Let me know if there are some further modifications.

2024-05-09 10:20 UTC, merged

2024-05-09 10:20 UTC, JuanSapriza commented
Thanks @NicCarp11 !! Good work!

2024-05-09 10:21 UTC, NicCarp11 commented
You're welcome!