Add latency estimations to simulator
esl-epfl/ESL-CGRA-simulator pull request #21
Opened 2024-07-10 09:56 UTC by maaspa

2024-07-10 12:18 UTC, JuanSapriza commented
@maaspa please add a detailed description including 
* What were the precise changes that you did
* Which tests did you run to check that it works
* What are the things the reviewer (me in this case) should test
* If there are any other pending tasks (in which case the PR should be converted to a **draft** )
*

2024-07-10 12:52 UTC, JuanSapriza requested changes
Nice job. Check the comments, which are mostly naming and placing. I think you approached really fast the kind of architecture i had in mind, well done! 
I hope you are seeing the advantages in clarity and scalability of doing it this way :smile:

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +operation_latency_mapping = {}
Could we move the latency-related operations to a separate module `latency.py`? 
It is unclear to me when this code is gonna execute (when loading the module probably). I would rather have a `latency_load_characterization( filename )` function, so we could actually have more than one possible characterization (for example, for the case where you wanna test different scenarios.

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +        self.instr_time = []
can we add units to all variables that refer to a magnitude? 
e.g. if `instr_time` is in seconds, rename it to `instr_time_s`

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +        self.instr_time = []
if instead it is in clock cycles, `instr_time_cc`, in which case might be better to call it `instr_latency_cc`

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +                    self.lw_count[c] += 1
I dont think this belongs here. This section of the code is controlling the operation of the instructions, and in the middle we are adding a section to count the number of memory accesses. Does not feel right, true? 
Probably there is a better place to do it. For example, given that we are saving all the history of operations, computing the number of memory access can very easily be done at the very end by simply counting how many times the operations appear in the instructions matrix. 

Regarding the `max_instr` i find it counter-intuitive. I understand that you are trying to check which cell of this instruction is the one that has the longest operation (therefore `max_instr` is to be read as `maximum latency of this instruction`). Had think quite a bit to see it this way. Additionally, given that several cells are doing LW, then why would one cell be the longest or not? It's weird to think and sounds kinda arbitrary. Will keep reading the code to see how it's used, but have a negative feeling about it. 

Regarding the `["LWI", ...]`, please define the array as a global variable with a name as `OPERATIONS_MEMORY_ACCESS`.

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +        lw_time = 0
why `lw_time` ? What happens with `sw` ? They are not distinguished? Are they the same to all effects?

2024-07-10 12:52 UTC, JuanSapriza commented on src/cgra.py
> +        if any(count >= 1 for count in self.lw_count):
why is the count carried out by column?

2024-07-11 10:15 UTC, maaspa commented on src/cgra.py
> +operation_latency_mapping = {}
Done, I added a function that can eventually be reused for other characterizations

2024-07-11 10:16 UTC, maaspa commented on src/cgra.py
> +        self.instr_time = []
Done :heavy_check_mark:

2024-07-11 10:20 UTC, maaspa commented on src/cgra.py
> +        self.lw_count = [0] * N_COLS
It was part of my previous memory latency algo which I have now removed. It is no longer in my code

2024-07-11 10:20 UTC, maaspa commented on src/cgra.py
> +                    self.lw_count[c] += 1
Done ✔️ (moved the code to a more appropriate place)

2024-07-11 10:21 UTC, maaspa commented on src/cgra.py
> +                if  self.max_instr is None or self.cells[r][c].time > self.max_instr.time:
Fixed units and added line that fetches latency  ✔️

2024-07-11 10:22 UTC, maaspa commented on src/cgra.py
> +        lw_time = 0
mem_latency_cc is now used to more generally regroup any memory access (as they have the same latency)

2024-07-11 10:22 UTC, maaspa commented on src/cgra.py
> +    def compute_mem_latency(self):
Done ✔️

2024-07-11 10:23 UTC, maaspa commented on src/cgra.py
> +        if any(count >= 1 for count in self.lw_count):
Refactored this part, lw_count is no more ✔️

2024-07-11 10:23 UTC, maaspa commented on src/cgra.py
> +    total_time = 0
Done ✔️

2024-07-11 10:23 UTC, maaspa commented on src/cgra.py
> +def display_characterization(cgra):
Done ✔️

2024-07-11 10:23 UTC, maaspa commented on src/cgra.py
> +            total_time += item.time
Done ✔️

2024-07-11 10:23 UTC, maaspa commented on src/cgra.py
> +            print("Cycle:", index + 1, "( ", item.instr2exec, " )")
Done ✔️

2024-07-11 10:23 UTC, maaspa commented on src/operation_characterization.csv
> +# operation_latency_mapping
Done ✔️

2024-07-15 07:39 UTC, JuanSapriza requested changes

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +        if (self.max_latency_instr.latency_cc > 2):
Why this tho?

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +    self.total_latency_cc += self.instr_latency_cc[-1].latency_cc
What's all this?

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +    print("Longest instructions per cycle:\n")
with "cycle" you mean "CGRA-cycle" (i.e. the execution of an instruction)? 
If an execution has 1256655 CGRA-cycles, we are gonna print them all? 
Why not make use of the system that is already implemented where the user can choose what to print? For example, I could call 
```
run(kernel_name, version=version, pr=["ROUT","OPS",  "OP_MAX_LAT", "TOTAL_LAT"  ], load_addrs=load_addrs, store_addrs=store_addrs)
```

Instead of forcing the user to see all the time everything

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +    self.max_latency_instr.latency_cc = max(self.max_latency_instr.latency_cc, mem_latency_cc)
I find it a little unhappy that this logic has to be hardcoded. This is easy now, but when we speak about the INTERLEAVED BUS you will not want to change the code to switch from one to other. What about this other approach:

`operation_characterization_N2M.csv`
```
TYPE, OPERATION, LATENCY, OVERHEAD, ADD_SAME_ROW, ADD_SAME_COL, ADD_CGRA, ADD_ADDR_SAME_INTEGER, ADD_ADDR_SAME_MODULO
0, NOP,  1, 0, 0, 0, 0, 0, 0
1, SADD, 1, 0, 0, 0, 0, 0, 0
1, SSUB, 1, 0, 0, 0, 0, 0, 0
2, SMUL, 3, 0, 0, 0, 0, 0, 0
3, LWD,  0, 2, 0, 1, 0, 1, 0
```
`operation_characterization_ONE2M.csv`
```
TYPE, OPERATION, LATENCY, OVERHEAD, ADD_SAME_ROW, ADD_SAME_COL, ADD_CGRA, ADD_ADDR_SAME_INTEGER, ADD_ADDR_SAME_MODULO
0, NOP,  1, 0, 0, 0, 0, 0, 0
1, SADD, 1, 0, 0, 0, 0, 0, 0
1, SSUB, 1, 0, 0, 0, 0, 0, 0
2, SMUL, 3, 0, 0, 0, 0, 0, 0
3, LWD,  0, 2, 0, 1, 1, 0, 0
```
Here you kind of embed the logic in the CSV and simplify the logic in the code, so if you want to test different architectures you dont need to modify the code. The example from above is the different bus topologies you already encountered (dont take this as is, as I could be wrong) 

The idea is that you encode in the different columns different latency patterns and how they are affected by operations of the same type. For example, `ADD_SAME_ROW` is the cc you add if you encounter another instruction of the same type in the same row, `ADD_ADDR_SAME_INTEGER` is, you take the target address, perform the integer division with the memory bank size and, if its the same, add 1 cc of penalty, same for the `MODULO` with the % modulo division (this will be useful for the interleaved memory banks. 

I'm not saying **DO IT LIKE THIS** ... but this kind of spirit that you will not want to change the code every time. It's something one day we will also do for the instruction operations to make the logic independent of the simulator so we can test different architecture changes without modifying the code. BTW.. the passion for not modifying the code is because we would like to have e.g. 20 different architectures and test which is the best.

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +def load_operation_characterization(operation_mapping, characterization_type):
why take operation mapping as a parameter?

2024-07-15 07:39 UTC, JuanSapriza commented on src/characterization.py
> +    self.max_latency_instr.latency_cc = max(self.max_latency_instr.latency_cc, mem_latency_cc)
actually, given how you implemented the fetch of the values, in the same CSV we could have different implementations: 
```
 #operation_latency_cc_mapping
. . . 

#operation_memory_interleaved_latency_cc_mapping
. . . 

```

2024-07-15 07:39 UTC, JuanSapriza commented on src/cgra.py
> +        self.max_latency_instr = None
If you have 3 LWD in the same instruction... you will just report the first LWD right? Why not report the instruction type instead? So you see if the blocking thing is the ALU or the MEM basically

2024-07-16 08:18 UTC, maaspa commented on src/characterization.py
> +        if (self.max_latency_instr.latency_cc > 2):
-The "max" function is used to only retain the largest operation (ie: between 3CC multiplication and only one 2CC memory operation, conserve the SMUL) 
-An instruction takes an extra CC if it contains the EXIT operation (= last instruction)

2024-07-16 08:22 UTC, maaspa commented on src/characterization.py
> +    self.total_latency_cc += self.instr_latency_cc[-1].latency_cc
First line: we need the current CGRA-cycle number as well as that of the instruction being executed (instr2exec)
Second line: Self.instr_latency is an array containing the longest operation for each instruction
Third line: With each instruction, we also sum up the total latency (to avoid doing so in the display_characterization function)

2024-07-16 08:23 UTC, maaspa commented on src/characterization.py
> +    print("Longest instructions per cycle:\n")
Good idea, I'm going to do this

2024-07-16 08:23 UTC, maaspa commented on src/characterization.py
> +def load_operation_characterization(operation_mapping, characterization_type):
Fixed ✔️

2024-07-16 08:23 UTC, maaspa commented on src/cgra.py
> +        self.max_latency_instr = None
Done ✔️

2024-08-06 15:06 UTC, maaspa commented
Changes: 
- The simulator now uses the bus type as a parameter to estimate the latency: 1-M, N-M, and interleaved bus types are supported. In the case of the 1-M bus, the conflicts between memory accesses and the CPU fetching code instructions impact latency. Currently, the simulator only estimates the latency due to the CPU polls regularly to check if the CGRA has finished executing.
- Simulator also estimates the configuration time before execution, as well as the time between the end of configuration and the start of execution iteration.
- User can specify the output information to be printed by using the  `pr` parameter.
Tests used to verify: The latency estimations were validated by testing the provided examples as well as my own personal test cases written previously (designed to identify and test challenging patterns). To further verify the accuracy of the estimations, the reviewer can try other kernels (or write new ones) and compare with the expected results simulated on HEEPsilon.

2024-08-08 08:26 UTC, JuanSapriza requested changes
We really improved the first stages of getting the latency. We now need to continue on the same path for the rest of the computation. From ordering the DMA accesses onwards is still seemingly too complex. 

I left some extra comment here and there you might also wanna check

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +            index_pos = int(((self.cells[r][c].addr - sorted(self.memory)[0][0]) / 4) % 8)
hmmmm.. what is saved in `cell.addr` if not the address that will be accessed? Shouldn't this differentiation be done before (when you compute the address in cgra.py? 

Now i'm also curious... reading and writing to RAM has the same latencies?

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +        index_pos = 1
Shouldn't this be `cell.addr/memory_size` where `memory_size` is not a constant but a property of a memory class for example? 

Maybe you should create a new class (even a new module) called `memory.py` where you define the memory class and where you can save the memory type, where you can move the functions to create the memory CSVs and where you keep the size and number of the banks.

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +        index_pos = 1
Note that in real life it's possible to have both non-interleaved and interleaved memory banks... ideally we should check if this address belongs to one or another... but let's simply add a big warning saying that the memory is HOMOGENEOUS

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +            index_pos = int(((self.cells[r][c].addr - self.init_store[0]) / 4) % 8)
why 4 and 8? What are those numbers?

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +    if self.bus_type != "INTERLEAVED":
Why does it matter if the memory is interleaved in the reordering of the DMA? The DMA does not know which memory architecture it will be targeting, so it seems weird that it affects something on how it orders operations.

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +    for r in range(N_ROWS):
So... when you explained me this logic you were just grabbing the operations and "moving them up"... This seems like just creating an NxN matrix and copying them "flattened"... why is such a complex logic required to this? I think these 4 functions could be a single one with 3 or 4 lines

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +    if total_mem_latency_cc > longest_alu_op_latency_cc:
and if not?

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +def get_latency_cc(self):
What is `self`? the cgra? the instruction? the operation? the cell? 

Note that `self` is a reserved parameter for the parent class instance. That is... 
```python
class Person:
   def __init__( self, height ):
       self.height = 0

   def get_height(self):
      return self.height


juan   = Person( 180 )
height = juan.get_height() 
```

`self` is a parameter YOU DO NOT PASS. It is passed automatically because its the instance of the containing method. Under no circumstances use `self` as a parameter name.

2024-08-08 08:26 UTC, JuanSapriza commented on src/characterization.py
> +def get_latency_cc(self):
Also because then you dont know what the parameter is... like was my case

2024-08-08 09:54 UTC, maaspa commented on src/cgra.py
> +    cgra.bus_type = next((item for item in BUS_TYPES if item in pr), "ONE-TO-M")
:heavy_check_mark:

2024-08-08 09:58 UTC, maaspa commented on src/characterization.py
> +            index_pos = int(((self.cells[r][c].addr - self.init_store[0]) / 4) % 8)
forgot to change those to constants thanks for the reminder :heavy_check_mark:

2024-08-08 10:00 UTC, maaspa commented on src/characterization.py
> +    if total_mem_latency_cc > longest_alu_op_latency_cc:
This if condition only serves to add "MEM" to the longest operation's name when the mem ops take longer than the non-mem ones. If this is not the case, then the name is just that of the longest non-mem operation.

2024-08-08 10:11 UTC, maaspa commented on src/characterization.py
> +def get_latency_cc(self):
Corrected self to "cgra" :heavy_check_mark:

2024-08-08 10:36 UTC, maaspa commented on src/characterization.py
> +        index_pos = 1
Created a memory module with all the relevant functions, that users can interact with directly from the notebook :heavy_check_mark:

2024-08-08 10:41 UTC, maaspa commented on src/characterization.py
> +    ACTIVE_ROW_COEF =  bus_type_active_row_coef[bus_type]
Yes they are constants

2024-08-08 12:22 UTC, maaspa commented on src/cgra.py
> +flag_poll_cnt = 0
fixed :heavy_check_mark:

2024-08-08 12:26 UTC, maaspa commented on src/characterization.py
> +    csv_file_path = os.path.join(script_dir, 'operation_characterization.csv')
:heavy_check_mark:

2024-08-08 12:29 UTC, maaspa commented on src/cgra.py
> +    display_characterization(cgra, pr)
The pr parameter takes in the different types of information the user wants to display. If a user doesn't want to print anything, he can do so by leaving the pr string array empty from the notebook.

2024-08-08 13:57 UTC, maaspa commented on src/characterization.py
> +    if self.bus_type != "INTERLEAVED":
moved to a more appropriate location :heavy_check_mark:

2024-08-19 12:14 UTC, JuanSapriza requested changes
I really like the progress! Well done. 
I left some more comments. I know you are now fixing some things with the CPU that were not working. 

Please, check this review comments and the previous ones, fix that problem with the CPU accesses and then I can proceed to doing tests to merge :)

2024-08-19 12:14 UTC, JuanSapriza commented on src/characterization.py
> +    base_addr = cgra.init_store[0] if cgra.cells[r][c].op == "SWD" else sorted(cgra.memory)[0][0]
I dont fully understand what this base address stands for, or why it's different for the SWD...

2024-08-19 12:14 UTC, JuanSapriza commented on src/characterization.py
> +        index_pos = cgra.cells[r][c].addr / cgra.memory_manager.bank_size
shouldnt the one-to-M be another case where the index is always the same (to simulate that they always get a conflict)?

2024-08-19 12:14 UTC, JuanSapriza commented on src/characterization.py
> +        index_pos = int(((cgra.cells[r][c].addr - base_addr) / cgra.memory_manager.spacing) % cgra.memory_manager.n_banks)
What is the `spacing`? if its how many bytes for each address, you may wanna call it `alignment_B` or `word_size_B` (my preferred)

2024-08-19 12:14 UTC, JuanSapriza commented on src/characterization.py
> +        index_pos = int(((cgra.cells[r][c].addr - base_addr) / cgra.memory_manager.spacing) % cgra.memory_manager.n_banks)
Add units to variables so that we know if they are in bits (b) , Bytes (B) or words of 4 bytes (w). My standard is to add it as a underscore and then the unit `word_size_B`, `banks_n` (with `n` standing for something that is just a count and therefore has no units)

2024-08-19 12:14 UTC, JuanSapriza commented on src/characterization.py
> +def compute_latency_cc(cgra, dependencies):
maybe wanna give it a name that refers to memory? because its not latency in general, but the latency of a memory access, i understand

2024-08-19 12:14 UTC, JuanSapriza commented on src/memory.py
> +    def __init__( self,bus_type="ONE-TO-M", spacing=4, n_banks=8, bank_size=32000):
nice. Just add the units

2024-08-19 12:14 UTC, JuanSapriza commented on src/memory.py
> +def kernel_clear_memory( name, version=""):
if you want, you can remove the work `kernel` from the beginning of these functions, as it does not make sense anymore. I like it more starting with memory as they are in the memory module.

2024-08-19 12:39 UTC, maaspa commented on src/characterization.py
> +    base_addr = cgra.init_store[0] if cgra.cells[r][c].op == "SWD" else sorted(cgra.memory)[0][0]
`base_addr` corresponds to the address of the first memory element  (`cgra_input[0][0]`). We need this value to find the position of the elements and ultimately return the corresponding bank index. (ie: 9th element accessed -> bank 0).
We need to handle SWD separately due to the starting address.

2024-08-19 13:18 UTC, maaspa commented on src/characterization.py
> +        index_pos = cgra.cells[r][c].addr / cgra.memory_manager.bank_size
:heavy_check_mark:

2024-08-19 13:18 UTC, maaspa commented on src/characterization.py
> +        index_pos = int(((cgra.cells[r][c].addr - base_addr) / cgra.memory_manager.spacing) % cgra.memory_manager.n_banks)
:heavy_check_mark:

2024-08-19 13:19 UTC, maaspa commented on src/characterization.py
> +def compute_latency_cc(cgra, dependencies):
:heavy_check_mark:

2024-08-19 13:19 UTC, maaspa commented on src/memory.py
> +    def __init__( self,bus_type="ONE-TO-M", spacing=4, n_banks=8, bank_size=32000):
:heavy_check_mark:

2024-08-19 13:19 UTC, maaspa commented on src/memory.py
> +def kernel_clear_memory( name, version=""):
:heavy_check_mark:

2024-08-21 14:07 UTC, JuanSapriza commented on src/characterization.py
> +    base_addr = cgra.init_store[0] if cgra.cells[r][c].op == "SWD" else sorted(cgra.memory)[0][0]
but why is the starting address related to the bank number?

2025-03-04 21:33 UTC, closed without merging